apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
type: Opaque
data: 
    postgres-user: YWtzaGF5Cg==
    postgres-password: cGFzc3dvcmQK
    postgres-db: ZWNvbW1lcmNlCg==
    #postgres-host: ZWNvbW1lcmNlCg==
    #postgres-port: aW4gNTQzMgo=


